import rclpy
from rclpy.node import Node
import tf2_ros
from visualization_msgs.msg import Marker, MarkerArray
from geometry_msgs.msg import TransformStamped
import time
import os
from scipy.spatial.transform import Rotation as R

class ComparePoseNode(Node):
    def __init__(self):
        super().__init__('compare_pose_node')
        
        self.tf_buffer = tf2_ros.Buffer()
        self.tf_listener = tf2_ros.TransformListener(self.tf_buffer, self)
        self.tf_broadcaster = tf2_ros.TransformBroadcaster(self) # TF Broadcaster 추가
        
        self.marker_pub = self.create_publisher(MarkerArray, '/remembered_tags', 10)
        
        self.timer = self.create_timer(0.1, self.timer_callback)
        
        self.tag_memory = {}
        self.box_memory = {}
        
        # Tags defined in tags_36h11_filter.yaml
        self.tag_frames = ['0', '1', '2', '3', '4', '5']
        
        # Boxes generated by golden_pose_node (assuming up to 10)
        self.box_frames = [f'box_{i}' for i in range(1, 11)]
        
        self.get_logger().info("Compare Pose Node started. Listening to TFs...")

    def get_transform(self, target_frame, source_frame):
        try:
            # We don't need a timeout here since we just want the latest available from the buffer
            t = self.tf_buffer.lookup_transform(
                target_frame,
                source_frame,
                rclpy.time.Time()
            )
            return t
        except tf2_ros.TransformException:
            return None

    def timer_callback(self):
        # 1. Look up AprilTag TFs
        for tag_frame in self.tag_frames:
            t = self.get_transform('base_link', tag_frame)
            if t is not None:
                pose = [
                    t.transform.translation.x,
                    t.transform.translation.y,
                    t.transform.translation.z,
                    t.transform.rotation.x,
                    t.transform.rotation.y,
                    t.transform.rotation.z,
                    t.transform.rotation.w
                ]
                self.tag_memory[tag_frame] = pose
                
        # 2. Look up Golden Pose TFs
        for box_frame in self.box_frames:
            t = self.get_transform('base_link', box_frame)
            if t is not None:
                pose = [
                    t.transform.translation.x,
                    t.transform.translation.y,
                    t.transform.translation.z,
                    t.transform.rotation.x,
                    t.transform.rotation.y,
                    t.transform.rotation.z,
                    t.transform.rotation.w
                ]
                self.box_memory[box_frame] = pose

        # 3. Publish markers for remembered AprilTags
        self.publish_tag_markers()
        
        # 4. Broadcast remembered TFs
        self.broadcast_remembered_poses()

    def broadcast_remembered_poses(self):
        now = self.get_clock().now().to_msg()
        
        # Explicit Rotation: Z 90, then X 90
        r_z_90 = R.from_euler('z', 90, degrees=True)
        r_x_90 = R.from_euler('x', 90, degrees=True)
        rot_offset = r_z_90 * r_x_90
        
        # Broadcast AprilTags
        for tag_id, pose in self.tag_memory.items():
            # 1. Original Remembered TF
            t_orig = TransformStamped()
            t_orig.header.stamp = now
            t_orig.header.frame_id = 'base_link'
            t_orig.child_frame_id = f'tag_{tag_id}_remembered'
            
            t_orig.transform.translation.x = float(pose[0])
            t_orig.transform.translation.y = float(pose[1])
            t_orig.transform.translation.z = float(pose[2])
            t_orig.transform.rotation.x = float(pose[3])
            t_orig.transform.rotation.y = float(pose[4])
            t_orig.transform.rotation.z = float(pose[5])
            t_orig.transform.rotation.w = float(pose[6])
            
            self.tf_broadcaster.sendTransform(t_orig)

            # 2. Rotated TF (Z 90, X 90)
            r_orig = R.from_quat([pose[3], pose[4], pose[5], pose[6]])
            r_rotated = r_orig * rot_offset
            q_rot = r_rotated.as_quat()

            t_rot = TransformStamped()
            t_rot.header.stamp = now
            t_rot.header.frame_id = 'base_link'
            t_rot.child_frame_id = f'tag_{tag_id}_rotated'
            
            t_rot.transform.translation.x = float(pose[0])
            t_rot.transform.translation.y = float(pose[1])
            t_rot.transform.translation.z = float(pose[2])
            t_rot.transform.rotation.x = float(q_rot[0])
            t_rot.transform.rotation.y = float(q_rot[1])
            t_rot.transform.rotation.z = float(q_rot[2])
            t_rot.transform.rotation.w = float(q_rot[3])
            
            self.tf_broadcaster.sendTransform(t_rot)
            
        # Broadcast Golden Boxes
        for box_id, pose in self.box_memory.items():
            t = TransformStamped()
            t.header.stamp = now
            t.header.frame_id = 'base_link'
            t.child_frame_id = f'{box_id}_remembered'
            
            t.transform.translation.x = float(pose[0])
            t.transform.translation.y = float(pose[1])
            t.transform.translation.z = float(pose[2])
            t.transform.rotation.x = float(pose[3])
            t.transform.rotation.y = float(pose[4])
            t.transform.rotation.z = float(pose[5])
            t.transform.rotation.w = float(pose[6])
            
            self.tf_broadcaster.sendTransform(t)

    def publish_tag_markers(self):
        marker_array = MarkerArray()
        
        # Delete old markers
        delete_marker = Marker()
        delete_marker.action = Marker.DELETEALL
        marker_array.markers.append(delete_marker)
        
        for idx, (tag_id, pose) in enumerate(self.tag_memory.items()):
            # Text Marker
            text_marker = Marker()
            text_marker.header.frame_id = 'base_link'
            text_marker.header.stamp = self.get_clock().now().to_msg()
            text_marker.ns = 'remembered_tags_text'
            text_marker.id = idx
            text_marker.type = Marker.TEXT_VIEW_FACING
            text_marker.action = Marker.ADD
            text_marker.pose.position.x = float(pose[0])
            text_marker.pose.position.y = float(pose[1])
            text_marker.pose.position.z = float(pose[2]) + 0.1 # slightly above the tag
            text_marker.scale.z = 0.05
            text_marker.color.r = 1.0
            text_marker.color.g = 0.0
            text_marker.color.b = 0.0
            text_marker.color.a = 1.0
            text_marker.text = f"Tag {tag_id}"
            
            # Cube Marker (Flat square representing the tag)
            cube_marker = Marker()
            cube_marker.header.frame_id = 'base_link'
            cube_marker.header.stamp = self.get_clock().now().to_msg()
            cube_marker.ns = 'remembered_tags_cube'
            cube_marker.id = idx + 100
            cube_marker.type = Marker.CUBE
            cube_marker.action = Marker.ADD
            cube_marker.pose.position.x = float(pose[0])
            cube_marker.pose.position.y = float(pose[1])
            cube_marker.pose.position.z = float(pose[2])
            cube_marker.pose.orientation.x = float(pose[3])
            cube_marker.pose.orientation.y = float(pose[4])
            cube_marker.pose.orientation.z = float(pose[5])
            cube_marker.pose.orientation.w = float(pose[6])
            
            # Tag size is 0.06m x 0.06m, thin thickness
            cube_marker.scale.x = 0.06
            cube_marker.scale.y = 0.06
            cube_marker.scale.z = 0.005 
            
            cube_marker.color.r = 1.0
            cube_marker.color.g = 0.0
            cube_marker.color.b = 0.0
            cube_marker.color.a = 0.8
            
            marker_array.markers.append(text_marker)
            marker_array.markers.append(cube_marker)
            
        if len(marker_array.markers) > 1:
            self.marker_pub.publish(marker_array)

    def save_to_file(self):
        filepath = "/home/irol/ros2_ws/src/HJ/golden_pose_tracker/pose_comparison_results.txt"
        self.get_logger().info(f"Saving pose comparison to: {filepath}")
        
        try:
            with open(filepath, 'w') as f:
                f.write("=== Pose Comparison Results ===\n")
                f.write(f"Saved at: {time.strftime('%Y-%m-%d %H:%M:%S')}\n\n")
                
                f.write("--- AprilTag Poses ---\n")
                if not self.tag_memory:
                    f.write("No AprilTags were detected.\n")
                for tag_id, pose in self.tag_memory.items():
                    # Original Pose
                    r_orig = R.from_quat([pose[3], pose[4], pose[5], pose[6]])
                    euler_orig = r_orig.as_euler('xyz', degrees=True)
                    
                    # Rotated Pose (Z 90, then X 90)
                    r_z_90 = R.from_euler('z', 90, degrees=True)
                    r_x_90 = R.from_euler('x', 90, degrees=True)
                    rot_offset = r_z_90 * r_x_90
                    
                    r_rotated = r_orig * rot_offset
                    euler_rot = r_rotated.as_euler('xyz', degrees=True)
                    
                    f.write(f"Tag {tag_id}:\n")
                    f.write(f"  [Original] Position (x,y,z): {pose[0]:.4f}, {pose[1]:.4f}, {pose[2]:.4f}\n")
                    f.write(f"  [Original] Orientation (Roll, Pitch, Yaw) [deg]: {euler_orig[0]:.2f}, {euler_orig[1]:.2f}, {euler_orig[2]:.2f}\n")
                    f.write(f"  [Rotated Z90X90] Orientation (Roll, Pitch, Yaw) [deg]: {euler_rot[0]:.2f}, {euler_rot[1]:.2f}, {euler_rot[2]:.2f}\n\n")
                    
                f.write("--- Golden Box Poses ---\n")
                if not self.box_memory:
                    f.write("No Golden Boxes were detected.\n")
                for box_id, pose in self.box_memory.items():
                    # Convert quaternion (qx, qy, qz, qw) to Euler (Roll, Pitch, Yaw) in degrees
                    r = R.from_quat([pose[3], pose[4], pose[5], pose[6]])
                    euler = r.as_euler('xyz', degrees=True)
                    
                    f.write(f"Box {box_id}:\n")
                    f.write(f"  Position (x,y,z): {pose[0]:.4f}, {pose[1]:.4f}, {pose[2]:.4f}\n")
                    f.write(f"  Orientation (Roll, Pitch, Yaw) [deg]: {euler[0]:.2f}, {euler[1]:.2f}, {euler[2]:.2f}\n\n")
                    
            print(f"\n[SUCCESS] Pose data saved to {filepath}\n")
        except Exception as e:
            self.get_logger().error(f"Failed to save file: {e}")

def main(args=None):
    rclpy.init(args=args)
    node = ComparePoseNode()
    
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        node.get_logger().info("Keyboard Interrupt detected. Saving file...")
    finally:
        node.save_to_file()
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()

if __name__ == '__main__':
    main()
