#!/usr/bin/env python3
"""
Fake MarkerArray publisher for testing intention_transform_node_ros2.py.

Publishes:
- Virtual boxes in map frame
- Real boxes in base_link frame

Real boxes are generated by adding random noise to the virtual box poses in map,
then transforming them into base_link using the current TF between map and base_link.

Required TF:
- map -> base_link must be available from localization or another TF publisher.

If USE_IDENTITY_FALLBACK_WHEN_TF_MISSING is True, identity transform is used when TF
is unavailable. This is only for standalone debugging.
"""

from __future__ import annotations

import copy
from dataclasses import dataclass
from typing import List, Optional

import numpy as np
from scipy.spatial.transform import Rotation as R

import rclpy
from rclpy.duration import Duration
from rclpy.node import Node
from rclpy.time import Time
from rclpy.qos import QoSProfile, qos_profile_system_default

from geometry_msgs.msg import Point, Pose, Quaternion, TransformStamped, Vector3
from std_msgs.msg import ColorRGBA, Header
from tf2_ros import Buffer, TransformException, TransformListener
from visualization_msgs.msg import Marker, MarkerArray

# =============================================================================
# Hard-coded configuration section
# =============================================================================

NODE_NAME = "fake_box_marker_array_publisher"

VIRTUAL_BOX_TOPIC = "/virtual_box"
REAL_BOX_TOPIC = "/real_box"

MAP_FRAME = "map"
BASE_FRAME = "base_link"

PUBLISH_RATE_HZ = 10.0
TF_LOOKUP_TIMEOUT_SEC = 0.05

SUBSCRIPTION_QOS: QoSProfile = qos_profile_system_default
PUBLISHER_QOS: QoSProfile = qos_profile_system_default

# If True, publish real boxes using identity map->base_link when TF is missing.
# For actual integration testing, keep this False so TF problems are visible.
USE_IDENTITY_FALLBACK_WHEN_TF_MISSING = False

# Random noise applied to the virtual box pose in map before transforming to base_link.
# Position noise is Gaussian [m]. Orientation noise is Gaussian [deg] in roll/pitch/yaw.
POSITION_NOISE_STD_M = np.array([0.005, 0.005, 0.005], dtype=float)
ORIENTATION_NOISE_STD_DEG = np.array([2.0, 2.0, 2.0], dtype=float)

# If True, noise is sampled once and then held fixed.
# If False, noise changes every publish cycle.
FIX_NOISE_ON_START = True

# Marker shape and visualization settings.
BOX_SCALE = Vector3(x=0.01, y=0.1, z=0.1)
VIRTUAL_BOX_COLOR = ColorRGBA(r=0.0, g=0.7, b=1.0, a=0.45)
REAL_BOX_COLOR = ColorRGBA(r=1.0, g=0.4, b=0.0, a=0.45)


# =============================================================================
# Input virtual box data
# =============================================================================


@dataclass(frozen=True)
class BoxSeed:
    marker_id: int
    name: str
    x: float
    y: float
    z: float
    qx: float
    qy: float
    qz: float
    qw: float


VIRTUAL_BOX_SEEDS: List[BoxSeed] = [
    BoxSeed(
        marker_id=1,
        name="sam3_box_1",
        x=-0.4932,
        y=0.0117,
        z=0.2603,
        qx=0.0,
        qy=0.0,
        qz=0.0,
        qw=1.0,
    ),
    BoxSeed(
        marker_id=2,
        name="sam3_box_2",
        x=-0.4928,
        y=-0.1511,
        z=0.2748,
        qx=0.0,
        qy=0.0,
        qz=0.0,
        qw=1.0,
    ),
    BoxSeed(
        marker_id=3,
        name="sam3_box_3",
        x=-0.4910,
        y=0.0126,
        z=0.4085,
        qx=0.0,
        qy=0.0,
        qz=0.0,
        qw=1.0,
    ),
]


# =============================================================================
# Math utilities
# =============================================================================


def normalize_quaternion_xyzw(q: np.ndarray) -> np.ndarray:
    q = np.asarray(q, dtype=float)
    norm = np.linalg.norm(q)
    if norm < 1e-12:
        return np.array([0.0, 0.0, 0.0, 1.0], dtype=float)
    return q / norm


def pose_to_matrix(pose: Pose) -> np.ndarray:
    q = normalize_quaternion_xyzw(
        np.array(
            [
                pose.orientation.x,
                pose.orientation.y,
                pose.orientation.z,
                pose.orientation.w,
            ],
            dtype=float,
        )
    )

    mat = np.eye(4, dtype=float)
    mat[:3, :3] = R.from_quat(q).as_matrix()
    mat[:3, 3] = np.array(
        [pose.position.x, pose.position.y, pose.position.z],
        dtype=float,
    )
    return mat


def matrix_to_pose(mat: np.ndarray) -> Pose:
    mat = np.asarray(mat, dtype=float)
    qx, qy, qz, qw = R.from_matrix(mat[:3, :3]).as_quat()

    return Pose(
        position=Point(
            x=float(mat[0, 3]),
            y=float(mat[1, 3]),
            z=float(mat[2, 3]),
        ),
        orientation=Quaternion(
            x=float(qx),
            y=float(qy),
            z=float(qz),
            w=float(qw),
        ),
    )


def transform_to_matrix(transform: TransformStamped) -> np.ndarray:
    t = transform.transform.translation
    q = transform.transform.rotation

    quat = normalize_quaternion_xyzw(np.array([q.x, q.y, q.z, q.w], dtype=float))

    mat = np.eye(4, dtype=float)
    mat[:3, :3] = R.from_quat(quat).as_matrix()
    mat[:3, 3] = np.array([t.x, t.y, t.z], dtype=float)
    return mat


def pose_from_seed(seed: BoxSeed) -> Pose:
    qx, qy, qz, qw = normalize_quaternion_xyzw(
        np.array([seed.qx, seed.qy, seed.qz, seed.qw], dtype=float)
    )

    return Pose(
        position=Point(x=seed.x, y=seed.y, z=seed.z),
        orientation=Quaternion(
            x=float(qx),
            y=float(qy),
            z=float(qz),
            w=float(qw),
        ),
    )


def add_noise_to_pose(pose: Pose, rng: np.random.Generator) -> Pose:
    base_mat = pose_to_matrix(pose)

    position_noise = rng.normal(loc=0.0, scale=POSITION_NOISE_STD_M, size=3)
    rpy_noise_rad = np.deg2rad(
        rng.normal(loc=0.0, scale=ORIENTATION_NOISE_STD_DEG, size=3)
    )

    noise_mat = np.eye(4, dtype=float)
    noise_mat[:3, :3] = R.from_euler("xyz", rpy_noise_rad, degrees=False).as_matrix()
    noise_mat[:3, 3] = position_noise

    # Right-multiply: noise is applied in the local box frame.
    noisy_mat = base_mat @ noise_mat
    return matrix_to_pose(noisy_mat)


def make_marker(
    marker_id: int,
    namespace: str,
    frame_id: str,
    pose: Pose,
    stamp,
    color: ColorRGBA,
) -> Marker:
    return Marker(
        header=Header(stamp=stamp, frame_id=frame_id),
        ns=namespace,
        id=marker_id,
        type=Marker.CUBE,
        action=Marker.ADD,
        pose=pose,
        scale=copy.deepcopy(BOX_SCALE),
        color=copy.deepcopy(color),
        lifetime=rclpy.duration.Duration(seconds=0.0).to_msg(),
        frame_locked=False,
    )


# =============================================================================
# Node
# =============================================================================


class FakeBoxMarkerArrayPublisher(Node):
    def __init__(self):
        super().__init__(NODE_NAME)

        self.tf_buffer = Buffer()
        self.tf_listener = TransformListener(self.tf_buffer, self)

        self.virtual_box_pub = self.create_publisher(
            MarkerArray,
            VIRTUAL_BOX_TOPIC,
            qos_profile=PUBLISHER_QOS,
        )
        self.real_box_pub = self.create_publisher(
            MarkerArray,
            REAL_BOX_TOPIC,
            qos_profile=PUBLISHER_QOS,
        )

        self.rng = np.random.default_rng()
        self.virtual_poses = [pose_from_seed(seed) for seed in VIRTUAL_BOX_SEEDS]

        if FIX_NOISE_ON_START:
            self.noisy_virtual_poses = [
                add_noise_to_pose(pose, self.rng) for pose in self.virtual_poses
            ]
        else:
            self.noisy_virtual_poses = None

        self.timer = self.create_timer(1.0 / PUBLISH_RATE_HZ, self.timer_callback)

        self.get_logger().info(
            f"{NODE_NAME} started. virtual_topic={VIRTUAL_BOX_TOPIC}, "
            f"real_topic={REAL_BOX_TOPIC}, frame={MAP_FRAME}->{BASE_FRAME}"
        )

    def lookup_base_from_map(self) -> Optional[np.ndarray]:
        try:
            # Returns transform that maps data from MAP_FRAME into BASE_FRAME.
            transform = self.tf_buffer.lookup_transform(
                BASE_FRAME,
                MAP_FRAME,
                Time(),
                timeout=Duration(seconds=TF_LOOKUP_TIMEOUT_SEC),
            )
            return transform_to_matrix(transform)
        except TransformException as exc:
            if USE_IDENTITY_FALLBACK_WHEN_TF_MISSING:
                self.get_logger().warn(
                    f"TF {BASE_FRAME} <- {MAP_FRAME} unavailable. "
                    f"Using identity fallback. Reason: {exc}"
                )
                return np.eye(4, dtype=float)

            self.get_logger().warn(
                f"TF {BASE_FRAME} <- {MAP_FRAME} unavailable. Real boxes not published. "
                f"Reason: {exc}"
            )
            return None

    def make_virtual_marker_array(self, stamp) -> MarkerArray:
        markers = []
        for seed, pose in zip(VIRTUAL_BOX_SEEDS, self.virtual_poses):
            markers.append(
                make_marker(
                    marker_id=seed.marker_id,
                    namespace="virtual_boxes",
                    frame_id=MAP_FRAME,
                    pose=pose,
                    stamp=stamp,
                    color=VIRTUAL_BOX_COLOR,
                )
            )
        return MarkerArray(markers=markers)

    def make_real_marker_array(self, stamp, T_base_map: np.ndarray) -> MarkerArray:
        if FIX_NOISE_ON_START:
            noisy_poses_map = self.noisy_virtual_poses
        else:
            noisy_poses_map = [
                add_noise_to_pose(pose, self.rng) for pose in self.virtual_poses
            ]

        markers = []
        for seed, noisy_pose_map in zip(VIRTUAL_BOX_SEEDS, noisy_poses_map):
            T_map_box_noisy = pose_to_matrix(noisy_pose_map)
            T_base_box = T_base_map @ T_map_box_noisy
            pose_base = matrix_to_pose(T_base_box)

            markers.append(
                make_marker(
                    marker_id=seed.marker_id,
                    namespace="real_boxes",
                    frame_id=BASE_FRAME,
                    pose=pose_base,
                    stamp=stamp,
                    color=REAL_BOX_COLOR,
                )
            )

        return MarkerArray(markers=markers)

    def timer_callback(self) -> None:
        stamp = self.get_clock().now().to_msg()

        virtual_markers = self.make_virtual_marker_array(stamp)
        self.virtual_box_pub.publish(virtual_markers)

        T_base_map = self.lookup_base_from_map()
        if T_base_map is None:
            return

        real_markers = self.make_real_marker_array(stamp, T_base_map)
        self.real_box_pub.publish(real_markers)


def main(args=None) -> None:
    rclpy.init(args=args)
    node = FakeBoxMarkerArrayPublisher()

    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
